### ISSUE TITLE
drop_duplicates support for RecordBatch

### ISSUE THREAD

**Issue by adarshshetty1** [TomScheffers/pyarrow_ops#4]
It would have been cool If the drop duplicates function or all the functions that supports pyarrow table also support pyarrow.RecordBatch like pyarrow.
https://arrow.apache.org/docs/python/generated/pyarrow.RecordBatch.html

**Comment by adarshshetty1** [comment]
Currently I'm getting the below error when trying to use the same:
```AttributeError: 'pyarrow.lib.RecordBatch' object has no attribute 'shape'```

**Comment by TomScheffers** [comment]
@adarshshetty1 Thanks for your suggestion. Pyarrow_ops has been a fun little project, however I realized it was not possible to create a performant dataframe libary besides my regular job, therefore I have stopped developing it. I would highly suggest that you look at [Polars](https://github.com/pola-rs/polars), which is a blazing fast libary for doing dataframe operations on Apache Arrow.

**Comment by adarshshetty1** [comment]
@TomScheffers Thanks for replying. I'll surely checkout Polars. Thanks for the suggestion. I'll also try to workaround with the issue I'm facing with some changes in this project. Btw nice project!
